[package]
name = "cephfs-find-wide-dirs"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5.15"
clap = { version = "4.5.53", features = ["derive"] }
log = "0.4.29"
env_logger = "0.11.8"
xattr = "1.6.1"
anyhow = "1.0.100"
